[package]
name = "lldb"
version = "0.1.0"
edition = "2021"

[dependencies]
cpp = "0.5"
bitflags = "1.0"
lazy_static = "1.3.0"
libc = "0.2.59"
num_enum = "0.5.7"

[build-dependencies]
cpp_build = "0.5"

[features]
weak-linkage = [] # weak-link to liblldb
